#!/usr/bin/env bash
# Prepare a merge of upstream (multica-ai/multica) into this fork's base
# branch, on a fresh `merge/upstream-<date>` branch.
#
# Usage:   scripts/upstream-merge.sh [--check-only]
# Effects: adds/points the `upstream` remote, fetches it, creates a
#          `merge/upstream-<date>` branch off the current base branch, and
#          runs `git merge upstream/<ref>` into it. A clean merge leaves a
#          normal merge commit; a conflicted merge is SNAPSHOTTED as a commit
#          that still contains conflict markers, so a human can check the
#          branch out and resolve.
# Output:  key=value lines to $GITHUB_OUTPUT when set (also echoed to stderr):
#            status         up_to_date | clean | conflicts
#            branch         merge branch name (empty when up_to_date)
#            behind         upstream commits not yet in base
#            conflict_count number of conflicted files (0 unless conflicts)
#          plus a `conflict_files` multiline block when there are conflicts.
#
# Config (env, all optional):
#   UPSTREAM_URL   default https://github.com/multica-ai/multica.git
#   UPSTREAM_REF   default main   (see docs/upstream-tracking.md — we track main)
#   MERGE_DATE     default $(date -u +%Y%m%d), overridable for reproducible runs
#
# Invoked by .github/workflows/upstream-tracking.yml; also runnable locally to
# drive the merge without a workflow round-trip. Follow the resolution steps in
# docs/upstream-tracking.md when the status is `conflicts`.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
cd "$ROOT"

UPSTREAM_URL="${UPSTREAM_URL:-https://github.com/multica-ai/multica.git}"
UPSTREAM_REF="${UPSTREAM_REF:-main}"
MERGE_DATE="${MERGE_DATE:-$(date -u +%Y%m%d)}"

CHECK_ONLY=0
if [[ "${1:-}" == "--check-only" ]]; then CHECK_ONLY=1; fi

emit() { # emit key value  -> $GITHUB_OUTPUT (if set) and stderr
  local key="$1" val="$2"
  echo "$key=$val" >&2
  if [[ -n "${GITHUB_OUTPUT:-}" ]]; then echo "$key=$val" >>"$GITHUB_OUTPUT"; fi
}

emit_multiline() { # emit_multiline key <<<"$value"
  local key="$1" val
  val="$(cat)"
  if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
    { echo "$key<<UPSTREAM_EOF"; echo "$val"; echo "UPSTREAM_EOF"; } >>"$GITHUB_OUTPUT"
  fi
}

# Point the `upstream` remote at the canonical URL (idempotent).
if git remote get-url upstream >/dev/null 2>&1; then
  git remote set-url upstream "$UPSTREAM_URL"
else
  git remote add upstream "$UPSTREAM_URL"
fi

echo "==> fetching upstream ($UPSTREAM_URL, ref $UPSTREAM_REF)" >&2
git fetch --quiet upstream "$UPSTREAM_REF"

BEHIND="$(git rev-list --count "HEAD..upstream/$UPSTREAM_REF")"
emit behind "$BEHIND"

# Already contains every upstream commit → nothing to do.
if git merge-base --is-ancestor "upstream/$UPSTREAM_REF" HEAD; then
  echo "==> base already up to date with upstream/$UPSTREAM_REF" >&2
  emit status up_to_date
  emit branch ""
  emit conflict_count 0
  exit 0
fi

echo "==> base is $BEHIND commit(s) behind upstream/$UPSTREAM_REF" >&2

if [[ "$CHECK_ONLY" -eq 1 ]]; then
  emit status behind
  exit 0
fi

BRANCH="merge/upstream-$MERGE_DATE"
git checkout -B "$BRANCH" >&2
emit branch "$BRANCH"

# Attempt the merge. Merge, never rebase — see docs/upstream-tracking.md.
if git merge --no-edit --no-ff "upstream/$UPSTREAM_REF" >&2; then
  echo "==> merge is clean" >&2
  emit status clean
  emit conflict_count 0
  exit 0
fi

# Conflicts. Snapshot the conflicted tree (markers included) so the branch is
# pushable and a human has a concrete starting point to resolve on.
CONFLICTS="$(git diff --name-only --diff-filter=U)"
COUNT="$(printf '%s\n' "$CONFLICTS" | grep -c . || true)"
echo "==> merge hit $COUNT conflicted file(s); snapshotting for manual resolution" >&2
printf '%s\n' "$CONFLICTS" >&2

git add -A
git commit --no-edit -m "merge upstream/$UPSTREAM_REF ($MERGE_DATE) — CONFLICTS, resolve before merge

Auto-generated by scripts/upstream-merge.sh. This commit still contains
conflict markers in $COUNT file(s). Do NOT merge as-is: check the branch out,
resolve per docs/upstream-tracking.md, then force-push." >&2

emit status conflicts
emit conflict_count "$COUNT"
emit_multiline conflict_files <<<"$CONFLICTS"
exit 0
